name: "Test"
on:
  workflow_dispatch:
    inputs:
      issue:
        description: 'Issue Number'
        required: true
        default: '4'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Body
        uses: peter-murray/issue-body-parser-action@v2
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.inputs.issue }}
          payload_marker: ghas_poc_object
      - name: Parse Issue Body
        run: |
          echo ${{ steps.issue_body_parser.outputs.payload }}
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Running a Test
        id: test
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SPECIAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.REPOSITORY }}
        with:
          issueBodyPayload: ${{ steps.issue_body_parser.outputs.payload }}
          approver: "NickLiffen"
          issueNumber: "1234"
          githubRepository: "nickliffen/create-sales-ops-issue"
